name: my_readme_updater
description: A sample flutter package that updates project structure in readme file whenever we run a git command.
version: 1.0.11
homepage: https://github.com/usmannaushahi/my_readme_updater
repository: https://github.com/usmannaushahi/my_readme_updater

environment:
  sdk: '>=3.0.5 <3.27.1'
  flutter: ">=1.10.0"


dependencies:
  args: ^2.6.0
  process_run: ^1.2.2+1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  my_readme_updater: my_readme_updater

