name: my_readme_updater
description: A sample flutter package that updates project structure in readme file whenever we run a git command.
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.5.5'

dependencies:
  args: ^2.6.0
  process_run: ^1.2.2+1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0


